[project]
name = "backend"
version = "0.0.1"
requires-python = ">=3.13,<3.14"
dependencies = [
    "uvicorn",
    "python-dotenv",
    "pydantic[email]",
    "django-simpleui",
    "django-ninja-jwt",
    "psycopg[binary,pool]",
]
